services:

  vault-hsm:
    image: hashicorp/vault-enterprise:1.21.4-ent
    container_name: vault-hsm
    ports:
      - "8201:8200"
    environment:
      VAULT_LICENSE: ${VAULT_LICENSE}
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault-hsm.hcl:/vault/config/vault.hcl
      - vault-hsm-data:/vault/data
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-net

  vault-main:
    image: hashicorp/vault-enterprise:1.21.4-ent
    container_name: vault-main
    depends_on:
      - vault-hsm
    ports:
      - "8200:8200"
    environment:
      VAULT_LICENSE: ${VAULT_LICENSE}
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_TRANSIT_SEAL_TOKEN: ${VAULT_HSM_TOKEN}
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault-main.hcl:/vault/config/vault.hcl
      - vault-main-data:/vault/data
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-net

volumes:
  vault-hsm-data:
  vault-main-data:

networks:
  vault-net:
    driver: bridge
