# Configuration for libvault-pkcs11.so (the Vault PKCS#11 provider).
# This file is read by the library at vault-main startup (mounted to /etc/vault-pkcs11.hcl).
# It tells the library how to connect to vault-hsm's KMIP endpoint.

slot {
  # vault-hsm KMIP listener — configured by init-hsm.sh
  server = "vault-hsm:5696"

  # mTLS client credentials — generated by init-hsm.sh and written to ./certs/
  tls_cert_path = "/vault/certs/vault-main-client-cert.pem"
  tls_key_path  = "/vault/certs/vault-main-client-key.pem"
  ca_path       = "/vault/certs/kmip-ca.pem"

  # KMIP scope created in init-hsm.sh
  scope = "sealing-key"
}
